version: "3.7"

services:
  recipe-app-db:
    image: mongo
    restart: always
    container_name: recipe-app-db
    ports:
      - 27017:27017
    volumes:
      - recipe-app-db:/data/db
    networks:
      - recipe-network

  recipe-app:
    image: devendra120/recipe-app1:buildprod123
    build:
      context: .
      target: prod
    container_name: recipe-app-prod
    restart: always
    volumes:
      - .:/app
    ports:
      - "80:5000"
    depends_on:
      - recipe-app-db
    environment:
      - MONGODB_URI=mongodb://recipe-app-db/recipe-app-db
    networks:
      - recipe-network

volumes:
  recipe-app-db:
    name: recipe-app-db

networks:
  recipe-network:
    name: recipe-network
